CXXFLAGS=-std=c++14 -I ../bridges/src/ -O3 -I ../includes
LDFLAGS=-l curl

LD=g++
CC=g++

bubble: 

weirdfibo:

depends:
	makedepend -I . -I ../includes -f Makefile *.cpp *.hpp

# DO NOT DELETE

bubble.o: ../includes/depgraph.hpp ../includes/depgraph_visualize.hpp
bubble.o: ../includes/depgraph_debug.hpp
weirdfibo.o: ../includes/depgraph.hpp ../includes/depgraph_visualize.hpp
weirdfibo.o: ../includes/depgraph_debug.hpp
